name: pyhail-test-env
channels:
 - conda-forge
dependencies:
 - numpy
 - scipy
 - arm_pyart
 - matplotlib
 - cartopy
 - numba>=0.59.1
 - ipython
 - ipykernel
 - ipywidgets
 - pytest
 - pip
 - pip:
   - pyodim
   - -e .