name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: test_environment.yml
          activate-environment: pyhail-test-env
          miniforge-version: latest

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: python -m pytest tests/ -v
